---
- hosts: local
  connection: local
  gather_facts: yes
  tasks:
    - name: build container image
      docker_image:
        name: "{{appname}}:{{appversion}}"
        build:
          path: "{{dockerproj}}"
          source: build
        state: present