---
- hosts: local
  connection: local
  gather_facts: no
  tasks:
 
      - name: Create a new EC2 key
        ec2_key:
            name: "{{keyname}}"
            region: "{{region}}"
        register: ec2_key_result
 
      - name: Save private key
        copy: content="{{ ec2_key_result.key.private_key }}" dest="~/controlproj/aws/{{keyname}}.pem" mode=0600
        when: ec2_key_result.changed