---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
 
      - name: Delete a EC2 key
        ec2_key:
            name: "{{keyname}}"
            region: "{{region}}"
#  absent means delete keypair
            state: absent
      - name: Delete existing dist folder
        file:
            path: "~/controlproj/aws/{{keyname}}.pem"
            state: absent
